@echo off
echo Set common environment variables...
set ZENWINX_VERSION=0,0,1,0
set ZENWINX_VERSION2="0, 0, 1, 0\0"
set ZENWINXVER=0.0.1
set MINGWBASE=D:\Software\MinGWStudio\MinGW
set MSVSBIN=D:\Software\Microsoft Visual Studio\VC98\Bin
set NETRUNTIMEPATH=C:\WINDOWS\Microsoft.NET\Framework\v2.0.50727
set SEVENZIP_PATH=C:\Program Files\7-Zip
set DDKINCDIR=D:\MyDocs\ReactOS030\include
set NSISDIR=D:\Software\Tools\NSIS
set WINDDKBASE=D:\WINDDK\3790~1.183
