@echo off
REM This script generates the "lang.ini" and "lang-classical.ini"  files
REM for the installer to always include the latest translations

set LangList=""

for %%L in ( "%~dp0\gui\i18n\*.lng" ) do call :CreateLangString "%%~nL"

call :CreateINI >"%~dp0\installer\lang.ini"

exit /B 0

:CreateLangString
    if %LangList% == "" (
        set LangList="ListItems=%~1"
    ) else (
        set LangList="%LangList:"=%^|%~1"
    )
goto :EOF

:CreateINI
    echo ; Ini file generated by the HM NIS Edit IO designer.
    echo [Settings]
    echo NumFields=3
    echo.
    echo [Field 1]
    echo Type=Label
    echo Text=Select a language pack to be used for UltraDefrag GUI.\r\n\r\nIf your native language is missing here or an existing translation is incomplete, feel free to submit your own translation. Your help will be much appreciated!
    echo Left=1
    echo Right=178
    echo Top=0
    echo Bottom=56
    echo.
    echo [Field 2]
    echo Type=Listbox
    echo Text=Listbox
    echo State=English (US)
    echo %LangList:"=%
    echo Left=182
    echo Right=297
    echo Top=0
    echo Bottom=139
    echo.
    echo [Field 3]
    echo Type=Link
    echo Text=Visit ultradefrag.wikispaces.com for more details...
    echo State=http://ultradefrag.wikispaces.com/
    echo Left=1
    echo Right=163
    echo Top=57
    echo Bottom=72
goto :EOF
