@echo off
echo Set common environment variables...
set ULTRADFGVER=1.2.3
set VERSION=1,2,3,0
set VERSION2="1, 2, 3, 0\0"
set NSISDIR=D:\Software\Tools\NSIS
set MSVSBIN=D:\Software\Microsoft Visual Studio\VC98\Bin
set DDKINCDIR=D:\MyDocs\ReactOS030\include
set WINDDKBASE=D:\WINDDK\3790~1.183
set NETRUNTIMEPATH=C:\WINDOWS\Microsoft.NET\Framework\v2.0.50727
set SEVENZIP_PATH=C:\Program Files\7-Zip
