@echo off
echo Set common environment variables...
set VERSION=3,2,2,0
set VERSION2="3, 2, 2, 0\0"
set ZENWINX_VERSION=0,1,1,0
set ZENWINX_VERSION2="0, 1, 1, 0\0"
set ULTRADFGVER=3.2.2
set ZENWINXVER=0.1.1
set WINDDKBASE=D:\WINDDK\3790~1.183
set MINGWBASE=D:\Software\MinGWStudio\MinGW
set NETRUNTIMEPATH=C:\WINDOWS\Microsoft.NET\Framework\v2.0.50727
set NSISDIR=D:\Software\Tools\NSIS
set SEVENZIP_PATH=C:\Program Files\7-Zip
set MSVSBIN=D:\Software\Microsoft Visual Studio\VC98\Bin
set DDKINCDIR=D:\MyDocs\ReactOS030\include
